### ISSUE TITLE
You can get stuck on the left or right sides of the game world

### ISSUE THREAD

**Issue by valkyrienyanko** [lorenzo774/sad-html-cat#1]
## Steps to Reproduce
1. move to far left or right
2. notice how you are stuck

**Comment by lorenzo774** [comment]
You mean when the browser window is not in focus?

**Comment by valkyrienyanko** [comment]
You can't move the cat while the browser is not in focus. So the browser has to be in focus in order to move the cat and get stuck on the far left or far right of the screen. My browser window was not in fullscreen when I was testing this. I'm using Libre Wolf browser.

**Comment by valkyrienyanko** [comment]
![image](https://user-images.githubusercontent.com/6277739/183301599-7319f684-8462-4d37-b0ad-62a74243773d.png)

**Comment by lorenzo774** [comment]
The cat needs to be inside the screen, it's not stuck.

**Comment by lorenzo774** [comment]
Maybe it's sad because it's stuck.
